name: workflow commands
on: [push]

jobs:
  variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set env variable
        run: echo ENV=This is the declared variable  >> $GITHUB_ENV
      - name: check env variable
        run: echo $ENV
      
      - name: status
        if: ${{ success() }}
        run: echo succeeded