name: conditional workflow
on: [push]
jobs:
    condition_met:
        #if: github.repository == 'RameshAU/workflow'
        if: github.repository == 'octo-org/octo-repo-prod'
        runs-on: ubuntu-latest
        steps:
            - name: true value
              run: echo success

    condition_notmet:
        runs-on: ubuntu-latest
        steps:
            - name: fail
              run: echo failure