name: dependent jobs
on: [push]

jobs:
  decom:
    needs: [build,up]
    runs-on: ubuntu-latest
    steps: 
      - name: decommission
        steps: 
          - run: echo server decommissioned
      - name: status
        if: ${{ success ()}}
        run: echo "code ran successfully"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        steps: 
          - run: echo server built
      - name: status
        if: ${{ success ()}}
        run: echo "code ran successfully"

  up:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: up
        steps: 
          - run: echo server up
      - name: status
        if: ${{ success ()}}
        run: echo "code ran successfully"