name: docker image pull
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: install docker
        run: apt install docker
      
      - name: status
        if: ${{ success() }}
        run: echo succeeded