name: docker image pull
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install docker
        run: sudo su - && apt install docker
      
      - name: status
        if: ${{ success() }}
        run: echo succeeded