name: Run Every Minute

on:
  schedule:
    - cron: '* * * * *'
workflow_dispatch:
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "This task runs every minute!"
