name: wworkflow commands
on: [push]

jobs:
  variable:
    runs-on: ubuntu-latest
    steps:
      - name: check env variable
        run: echo ENV=five >> $GITHUB_ENV
      - name: check env variable
        run: echo $ENV
      
      - name: status
        if: ${{ success() }}
        run: echo succeeded